### ISSUE TITLE
copyfiles is not recognized

### ISSUE THREAD

**Issue by 5T3EF4N** [nekiro/Nekiro-Rcc-Editor#2]
It's giving me this error when I try to run it.

> nekirosrcceditor@1.0.0 compile
> tsc && copyfiles src/html/*.html src/css/*.css src/assets/* src/rcc/rcc.exe build

'copyfiles' is not recognized as an internal or external command,
operable program or batch file.

**Comment by nekiro** [comment]
npm install -g copyfiles

I'll add this as dev dependency, so it's auto installed.
